export declare class BxAutocompleteRequest {
    protected language: string;
    protected queryText: string;
    protected choiceId: string;
    protected textualSuggestionsHitCount: number;
    protected bxSearchRequest: any;
    protected highlight: boolean;
    protected highlightPre: string;
    protected highlightPost: string;
    private propertyQueries;
    protected indexId: string;
    constructor(language: string, queryText: string, textualSuggestionsHitCount: number, productSuggestionHitCount?: number, autocompleteChoiceId?: string, searchChoiceId?: string, highlight?: boolean, highlightPre?: string, highlightPost?: string);
    getBxSearchRequest(): any;
    setBxSearchRequest(bxSearchRequest: any): void;
    getLanguage(): string;
    setLanguage(language: string): void;
    getQuerytext(): string;
    setQuerytext(queryText: string): void;
    getChoiceId(): string;
    setChoiceId(choiceId: string): void;
    getTextualSuggestionHitCount(): number;
    setTextualSuggestionHitCount(textualSuggestionsHitCount: number): void;
    getIndexId(): string;
    setIndexId(indexId: string): void;
    setDefaultIndexId(indexId: string): void;
    getHighlight(): boolean;
    getHighlightPre(): string;
    getHighlightPost(): string;
    private getAutocompleteQuery;
    addPropertyQuery(field: string, hitCount: number, evaluateTotal?: boolean): void;
    resetPropertyQueries(): void;
    getAutocompleteThriftRequest(profileid: string, thriftUserRecord: string): any;
}
