export declare class BxChooseResponse {
    private response;
    private bxRequests;
    private notifications;
    constructor(response: any, _bxRequests?: any);
    protected notificationLog: any[];
    protected notificationMode: boolean;
    setNotificationMode(mode: any): void;
    getNotificationMode(): boolean;
    addNotification(name: any, parameters: any): void;
    getNotifications(): any;
    getResponse(): any;
    getChoiceResponseVariant(choice?: null, count?: number): any;
    getChoiceIdFromVariantIndex(variant_index: any): any;
    protected getChoiceIdResponseVariant(id?: any): any;
    getFirstPositiveSuggestionSearchResult(variant: any, maxDistance?: number): null;
    getVariantSearchResult(variant: any, considerRelaxation?: boolean, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchResultHitVariable(searchResult: any, hitId: any, field: string): null;
    getSearchResultHitFieldValue(searchResult: any, hitId: any, fieldName?: string): null;
    getSearchResultHitIds(searchResult: any, fieldId?: string): any;
    getHitExtraInfo(choice?: any, hitId?: number, info_key?: string, default_value?: string, count?: number, considerRelaxation?: boolean, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getHitVariable(choice?: any, hitId?: number, field?: string, count?: number, considerRelaxation?: boolean, maxDistance?: number, discardIfSubPhrases?: boolean): null;
    getHitFieldValue(choice?: any, hitId?: number, fieldName?: string, count?: number, considerRelaxation?: boolean, maxDistance?: number, discardIfSubPhrases?: boolean): null;
    getHitIds(choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, fieldId?: string, discardIfSubPhrases?: boolean): any;
    retrieveHitFieldValues(item: any, field: string, fields: any, hits: string[]): any;
    Array_keys(input: any): any[];
    getSearchHitFieldValues(searchResult: any, fields: string[]): any;
    getRequestFacets(choice?: any): any;
    getFacets(choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getHitFieldValues(fields: any, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getFirstHitFieldValue(field?: any, returnOneValue?: boolean, hitIndex?: number, choice?: any, count?: number, maxDistance?: number): any;
    getTotalHitCount(choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    areResultsCorrected(choice?: any, count?: number, maxDistance?: number): boolean;
    areResultsCorrectedAndAlsoProvideSubPhrases(choice?: any, count?: number, maxDistance?: number): boolean;
    getCorrectedQuery(choice?: any, count?: number, maxDistance?: number): any;
    getResultTitle(choice?: any, count?: number, ddefault?: string): any;
    areThereSubPhrases(choice?: any, count?: number, maxBaseResults?: number): boolean;
    getSubPhrasesQueries(choice?: any, count?: number): any;
    getSubPhraseSearchResult(queryText: string, choice?: any, count?: number): null;
    getSubPhraseTotalHitCount(queryText: string, choice?: any, count?: number): any;
    getSubPhraseHitIds(queryText: string, choice?: any, count?: number, fieldId?: string): any;
    getSubPhraseHitFieldValues(queryText: string, fields: string[], choice?: any, considerRelaxation?: boolean, count?: number): any;
    toJson(fields: string[]): string;
    getSearchResultExtraInfo(searchResult: any, extraInfoKey: any, defaultExtraInfoValue?: any): any;
    mergeJourneyParams(parentParams: any, childParams: any): any;
    getCPOJourney(choice_id?: any): any;
    getStoryLine(choice_id?: any): any;
    getParameterValuesForVisualElement(element: any, paramName: string): null;
    getNarrativeDependencies(choice_id?: any): any;
    getNarratives(choice_id?: any): any[];
    getOverwriteParams(parameters: any): any;
    prepareVisualElement(render: any, overwriteParams: any): any;
    propagateParams(acts: any, params: any): any;
    getVariantExtraInfo(variant: any, extraInfoKey: any, defaultExtraInfoValue?: any): any;
    getExtraInfo(extraInfoKey: any, defaultExtraInfoValue?: any, choice?: any, considerRelaxation?: any, count?: any, maxDistance?: any, discardIfSubPhrases?: any): any;
    ucfirst(str: any): string;
    prettyPrintLabel(label: any, prettyPrint?: any): any;
    getLanguage(defaultLanguage?: string): any;
    getExtraInfoLocalizedValue(extraInfoKey: any, language?: any, defaultExtraInfoValue?: any, prettyPrint?: any, choice?: any, considerRelaxation?: any, count?: any, maxDistance?: any, discardIfSubPhrases?: any): any;
    getSearchMessageTitle(language?: any, defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageDescription(language?: any, defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageTitleStyle(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageDescriptionStyle(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageContainerStyle(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageLinkStyle(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageSideImageStyle(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageMainImageStyle(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageMainImage(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageSideImage(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageLink(language?: any, defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getRedirectLink(language?: any, defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageGeneralCss(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getSearchMessageDisplayType(defaultExtraInfoValue?: any, prettyPrint?: boolean, choice?: any, considerRelaxation?: boolean, count?: number, maxDistance?: number, discardIfSubPhrases?: boolean): any;
    getLocalizedValue(values: any, key?: any): any;
}
